# configuration
# last changed: 2026-05-07 18:50:58

title: Hannes Schoss
email: hannes.schoss@student.uni-tuebingen.de
description: >- # this means to ignore newlines until "baseurl:"
  Personal Website for documenting projects, work and interests. 
baseurl: ""
url: https://hschoss.github.io
github_username: hschoss

# Build settings
theme: minima
plugins:
  - jekyll-feed
